//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaptivePaymentsSampleApp.UseCaseSamples {
    
    public partial class PreapprovalPayment {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected AjaxControlToolkit.ToolkitScriptManager ScriptManagerPreapprovalPayment;
        protected System.Web.UI.WebControls.TextBox currencyCode;
        protected System.Web.UI.WebControls.TextBox startingDate;
        protected System.Web.UI.WebControls.ImageButton ImageButtonStartingDate;
        protected AjaxControlToolkit.CalendarExtender CalendarExtenderStartingDate;
        protected System.Web.UI.WebControls.TextBox endingDate;
        protected System.Web.UI.WebControls.ImageButton ImageButtonEndingDate;
        protected AjaxControlToolkit.CalendarExtender CalendarExtenderEndingDate;
        protected System.Web.UI.WebControls.TextBox cancelURL;
        protected System.Web.UI.WebControls.TextBox returnURL;
        protected System.Web.UI.WebControls.TextBox ipnNotificationURL;
        protected System.Web.UI.WebControls.TextBox senderEmail;
        protected System.Web.UI.WebControls.TextBox dateOfMonth;
        protected System.Web.UI.WebControls.DropDownList dayOfWeek;
        protected System.Web.UI.WebControls.TextBox maxAmountPerPayment;
        protected System.Web.UI.WebControls.TextBox maxNumberOfPayments;
        protected System.Web.UI.WebControls.TextBox maxNumberOfPaymentsPerPeriod;
        protected System.Web.UI.WebControls.TextBox totalAmountOfAllPayments;
        protected System.Web.UI.WebControls.DropDownList paymentPeriod;
        protected System.Web.UI.WebControls.DropDownList displayMaxTotalAmount;
        protected System.Web.UI.WebControls.Button ButtonAdaptivePayments;
        protected System.Web.UI.WebControls.HyperLink HyperLinkHome;
        protected System.Web.UI.WebControls.HyperLink HyperLinkBack;
    }
}
