//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaptivePaymentsSampleApp.UseCaseSamples {
    
    public partial class SimplePayment {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.TextBox currencyCode;
        protected System.Web.UI.WebControls.DropDownList actionType;
        protected System.Web.UI.WebControls.TextBox cancelURL;
        protected System.Web.UI.WebControls.TextBox returnURL;
        protected System.Web.UI.WebControls.TextBox ipnNotificationURL;
        protected System.Web.UI.WebControls.TextBox senderEmail;
        protected System.Web.UI.WebControls.TextBox amount;
        protected System.Web.UI.WebControls.TextBox mail;
        protected System.Web.UI.WebControls.Button ButtonAdaptivePayments;
        protected System.Web.UI.WebControls.HyperLink HyperLinkHome;
        protected System.Web.UI.WebControls.HyperLink HyperLinkBack;
    }
}
